"""empty message

Revision ID: 53e74374df29
Revises: None
Create Date: 2014-12-09 16:28:00.907720

"""

# revision identifiers, used by Alembic.
revision = '53e74374df29'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
